"""empty message

Revision ID: 51747515d21b
Revises: 21468f4a424e
Create Date: 2023-01-16 00:16:34.558726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51747515d21b'
down_revision = '21468f4a424e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        batch_op.create_unique_constraint("email", ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint("email", type_='unique')
        batch_op.drop_column('email')


    # ### end Alembic commands ###
